title: It Was Only 99 Cents
author: Dakota Stuart
email: dakotastuart99@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The year was 2018, it was a dark and stormy night and all I wanted was Sunny D. As I walk twords the Sunny D in the dark and empty store I see that the Sunny D is 
  99 cents with joy I crack the seal and chug. All of the suden everything is bright and then everyone dies.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-time-machine
